version: "2.2"

services:
  es01:
    image: elasticsearch:8.6.0
    container_name: es01
    user: $UID:$GID
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es01
      - discovery.type=single-node
      - discovery.seed_hosts=[]
      - bootstrap.memory_lock=true
      - ingest.geoip.downloader.enabled=false
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- "ELASTIC_PASSWORD=1234"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic-data:/var/share/elasticsearch/data
      - elastic-logs:/usr/share/elasticsearch/logs
    networks:
      - elastic-net

  kibana:
    image: kibana:8.6.0
    container_name: kibana
    user: $UID:$GID
    depends_on:
      - es01
    #environment:
    #  - "ELASTICSEARCH_USERNAME=elastic"
    #  - "ELASTICSEARCH_PASSWORD=1234"
    ports:
      - 5601:5601
    networks:
      - elastic-net

volumes:
  elastic-data:
  elastic-logs:

networks:
  elastic-net:
