version: "2.2"

services:
  es01:
    image: elasticsearch:${STACK_VERSION}
    container_name: es01
    user: ${UID}:${GID}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=es01
      - discovery.type=single-node
      - discovery.seed_hosts=[]
      - bootstrap.memory_lock=true
      - ingest.geoip.downloader.enabled=false
      - xpack.ml.enabled=false
      # - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --cacert /usr/share/elasticsearch/config/certs/http_ca.crt https://localhost:9200 | grep --quiet 'missing authentication credentials'"
        ]
      interval: 60s
      timeout: 10s
      retries: 3
    ports:
      - "${ES_PORT}:9200"
    volumes:
      - es01-data:/usr/share/elasticsearch/data
      - es01-logs:/usr/share/elasticsearch/logs
    networks:
      - elastic-net

  kibana:
    image: kibana:${STACK_VERSION}
    container_name: kibana
    user: ${UID}:${GID}
    depends_on:
      es01:
        condition: service_healthy
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - elastic-net

volumes:
  es01-data:
  es01-logs:

networks:
  elastic-net:
