ARG PHOTON_VERSION=4.0
FROM photon:${PHOTON_VERSION}

WORKDIR /scratch
ARG REQUIREMENTS
COPY ${REQUIREMENTS} Requirements.txt

RUN tdnf --assumeyes update \
    && tdnf --assumeyes install $(cat Requirements.txt) \
    && tdnf clean all
