ARG PHOTON_VERSION=4.0
FROM photon:${PHOTON_VERSION}

WORKDIR /scratch
ARG REQUIREMENTS
COPY ${REQUIREMENTS} Requirements.txt

RUN tdnf --assumeyes update \
    && tdnf --assumeyes install $(cat Requirements.txt) \
    && tdnf clean all


##
##  PhotoOS does not have pre-compiled YARA package.
##  We must rebuild it from source code.
##
ARG YARA_PREFIX=/opt/yara
ARG YARA_VERSION=4.2.3
ARG YARA_SHA256=1cd84fc2db606e83084a648152eb35103c3e30350825cb7553448d5ccde02a0d
ARG YARA_TARBALL=v${YARA_VERSION}.tar.gz
ARG YARA_URL=https://github.com/VirusTotal/yara/archive/refs/tags/${YARA_TARBALL}
LABEL yara_url=${YARA_URL}
LABEL yara_version=${YARA_VERSION}
LABEL yara_sha25=${YARA_SHA256}

WORKDIR /scratch
RUN curl -L -O ${YARA_URL} \
    && echo "${YARA_SHA256}  ${YARA_TARBALL}" | sha256sum --check \
    && mkdir -p /scratch/yara \
    && tar --extract --file=${YARA_TARBALL} --directory=/scratch/yara --strip-components=1

WORKDIR /scratch/yara
RUN ./bootstrap.sh \
    && ./configure \
        --prefix=${YARA_PREFIX} \
        --enable-static \
    && make \
    && make install

ENV PATH="${YARA_PREFIX}/bin:$PATH"
ENV LD_LIBRARY_PATH="${YARA_PREFIX}/lib:$LD_LIBRARY_PATH"

##
##  PhotoOS does not have pre-compiled libmaxminddb package.
##  We must rebuild it from source code.
##
##  WONTFIX: Tarball from https://github.com/maxmind/libmaxminddb/archive/refs/tags/1.7.1.tar.gz is missing `libtap/tap.h` and other Git submodules.
##  Recursive Git clone the repo instead.
##
ARG MAXMINDDB_PREFIX=/opt/maxminddb
ARG MAXMINDDB_VERSION=1.7.1
ARG MAXMINDDB_REPO=https://github.com/maxmind/libmaxminddb
LABEL maxminddb_repo=${MAXMINDDB_REPO}
LABEL maxminddb_version=${MAXMINDDB_VERSION}

WORKDIR /scratch
RUN git clone --recursive ${MAXMINDDB_REPO}

WORKDIR /scratch/libmaxminddb
RUN git checkout ${MAXMINDDB_VERSION} \
    && ./bootstrap \
    && ./configure \
        --prefix=${MAXMINDDB_PREFIX} \
        --enable-tests \
    && make \
    && make check \
    && make install

ENV PATH="${MAXMINDDB_PREFIX}/bin:$PATH"
ENV LD_LIBRARY_PATH="${MAXMINDDB_PREFIX}/lib:$LD_LIBRARY_PATH"


##
##  KISS: Use pre-compiled NodeJS, version must be 16
##
ARG NODE_PREFIX=/opt/nodejs
ARG NODE_VERSION=16.18.1
ARG NODE_SHA256=de2c694e7081c37022817d27a65b02f69ecf4c49699d65585e8e24431b7bc920
ARG NODE_TARBALL=node-v${NODE_VERSION}-linux-x64.tar.xz
ARG NODE_URL=https://nodejs.org/download/release/v${NODE_VERSION}/${NODE_TARBALL}
LABEL node_url=${NODE_URL}
LABEL node_version=${NODE_VERSION_TAG}
LABEL node_sha256=${NODE_SHA256}

WORKDIR /scratch
RUN curl -O ${NODE_URL} \
    && echo "${NODE_SHA256}  ${NODE_TARBALL}" | sha256sum --check \
    && mkdir -p ${NODE_PREFIX} \
    && tar --extract --file=${NODE_TARBALL} --directory=${NODE_PREFIX} --strip-components=1

ENV PATH="${NODE_PREFIX}/bin:$PATH"
